export var data = [
    {
        id: 1,
        firstName: 'Ssembatya',
        lastName: 'Isaac',
        genderName: 'Male',
        category: 'Positive',
        healthofficer_id: 4,
        hospital: 'Mulago',
        district: 'Kampala',
    },
    {
        id: 2,
        firstName: 'Kigula',
        lastName: 'Jesse',
        genderName: 'Male',
        category: 'False Positive',
        healthofficer_id: 1,
        hospital: 'IHK',
        district: 'Kampala',
    },
    {
        id: 3,
        firstName: 'Namujumbi',
        lastName: 'Sunita',
        genderName: 'Female',
        category: 'Postive',
        healthofficer_id: 2,
        hospital: 'Mulago',
        district: 'Kampala',
    },
    {
        id: 4,
        firstName: 'Ndyabagye',
        lastName: 'Henry',
        genderName: 'Male',
        category: 'False Positive',
        healthofficer_id: 5,
        hospital: 'Norvik',
        district: 'Mbale',
    },
    {
        id: 5,
        firstName: 'Opio',
        lastName: 'Andrew',
        genderName: 'Male',
        category: 'Negative',
        healthofficer_id: 3,
        hospital: 'Norvik',
        district: 'Kabale',
    },
    {
        id: 6,
        firstName: 'McCarthy',
        lastName: 'Mutebi',
        genderName: 'Male',
        category: 'Negative',
        healthofficer_id: 4,
        hospital: 'UMK',
        district: 'Gulu',
    },
    {
        id: '7',
        firstName: 'Nanita',
        lastName: 'Nalule',
        genderName: 'Female',
        category: 'False postive',
        healthofficer_id: 4,
        hospital: 'NHS',
        district: 'Wakiso',
    },
    {
        id: 8,
        firstName: 'Manyinza',
        lastName: 'Hannah',
        genderName: 'Female',
        category: 'Negative',
        healthofficer_id: 6,
        hospital: 'Aga Khan',
        district: 'Wakiso',
    },
    {
        id: 9,
        firstName: 'Amokol',
        lastName: 'Priscilla',
        genderName: 'Male',
        category: 'Positive',
        healthofficer_id: 3,
        hospital: 'Aga Khan',
        district: 'Wakiso',
    },
    {
        id: 10,
        firstName: 'Namayanja',
        lastName: 'Zahara',
        genderName: 'Female',
        category: 'Negative',
        healthofficer_id: 3,
        hospital: 'Mulago',
        district: 'Kampala',
    },
    {
        id: 11,
        firstName: 'Kyeyune',
        lastName: 'Denzil',
        genderName: 'Male',
        category: 'Positive Female',
        healthofficer_id: 2,
        hospital: 'Mulago',
        district: 'Kampala',
    },
]